server:
  port: 3300

logging:
  level:
    org.springframework.jdbc: debug

spring:
  profiles:
    active: @active.profile@

  application:
    name: @project.name@

  output:
    ansi:
      enabled: always

  datasource:
    platform: H2
    data: classpath*:db/h2/data-h2.sql
    schema: classpath*:db/h2/schema-h2.sql

  jdbc:
    template:
      fetch-size: 100

classifier:
  data-update:
    enabled: true
    initial-delay: 60000
    fixed-rate: 60000
