server:
  port: 3300

spring:
  profiles:
    active: @active.profile@
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always

  datasource:
    platform: HSQLDB
    data: classpath*:db/h2/data.sql
    schema: classpath*:db/h2/schema.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

classifier:
  data-update:
    enabled: true
    initial-delay: 60000
    fixed-rate: 60000
