server:
  port: 8080

api:
  name: @project.name@
  description: @project.description@
  version: @project.version@

logging:
  level:
    org.springframework.jdbc: debug
    org.springframework.web: debug
    org.apache.http: debug

spring:
  profiles:
    active: @active.profile@

  application:
    name: @project.name@

  output:
    ansi:
      enabled: always

  datasource:
    platform: H2
    data: classpath*:db/h2/data.sql
    schema: classpath*:db/h2/schema.sql

  jdbc:
    template:
      fetch-size: 100

classifier:
  default:
    sub-category-id: 0

  data-update:
    enabled: true
    initial-delay: 60000
    fixed-rate: 60000
