server:
  port: 8080

api:
  name: @project.name@
  description: @project.description@
  version: @project.version@

logging:
  level:
    root: INFO
    org.springframework.web: info
    org.springframework.jdbc: info

spring:
  profiles:
    active: @active.profile@

  application:
    name: @project.name@

  output:
    ansi:
      enabled: always

  main:
    banner-mode: "off"

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${MSSQL_DB_CLASSIFIER_URL}
    hikari:
      username: ${MSSQL_DB_CLASSIFIER_USERNAME}
      password: ${MSSQL_DB_CLASSIFIER_PASSWORD}
      maximum-pool-size: 4

  jdbc:
    template:
      fetch-size: 100

classifier:
  default:
    sub-category-id: 0

  data-update:
    enabled: true
    initial-delay: 60000
    fixed-rate: 60000
